import './globals.css';
import NavbarWrapper from './(components)/NavbarWrapper';

export const metadata = {
  title: 'Travel Itinerary App',
  description: 'Generated by Tarun',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
