services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - MONGO_URI=mongodb+srv://alweena:eLhXdauwyGuK8nD1@testcluster.g5huafi.mongodb.net/itinerarydb
      - JWT_SECRET=supersecretkey

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
